Martin-Pollitos-School-REST-JpaRepository
fjpgtt/pollitos-school pull request #5
Opened 2024-11-22 21:23 UTC by Martin-Mtz

2024-11-27 09:22 UTC, fjpgtt requested changes

2024-11-27 09:22 UTC, fjpgtt commented on data/school.mv.db
These files should not be uploaded

2024-11-27 09:22 UTC, fjpgtt commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
You are adding this one twice

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/Config/AppConfig.java
> +    CommandLineRunner initDatabase( SchoolRepository schoolRepository, StudentRepository studentRepository, CourseRepository courseRepository,  GradeRepository gradeRepository) {
Why you change this to CommandLineRunner?

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/controller/ApplicationExceptionHandler.java
> +        Map<String, String> errorMap = new HashMap<>();
Add logs

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/model/Course.java
> +@Entity(name = "courses")
You should also add Table annotation

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/model/Course.java
> +    @ManyToOne
You need to make the relationshio lazy

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/model/School.java
> +    private String name;
Right now is not neccessary but you can create the mapping to Course and Student

2024-11-27 09:22 UTC, fjpgtt commented on src/main/java/com/iwaconsolti/school/demo/repository/CourseRepository.java
> +    record CourseDTO(int id, String name, String professorName){}
It is better to have a class that has this entity, since is used aoutside of the repository

2024-11-28 23:46 UTC, Martin-Mtz commented on src/main/java/com/iwaconsolti/school/demo/Config/AppConfig.java
> +    CommandLineRunner initDatabase( SchoolRepository schoolRepository, StudentRepository studentRepository, CourseRepository courseRepository,  GradeRepository gradeRepository) {
I couldn't make it run with postconstruct, but that's it

2025-02-17 20:25 UTC, closed without merging